---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: mfsmount
  name: mfsmount
  namespace: moosefs
spec:
  selector:
    matchLabels:
      app: mfsmount
  template:
    metadata:
      labels:
        app: mfsmount
    spec:
      containers:
      - env:
        - name: MFSMASTER
          value: mfsmaster.default
        - name: MFSPATH
          value: /moosefs-kubernetes
        image: poeyashi/mfsmount:3.0.99-1
        name: mfsmount
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/fuse
          name: fuse
          # set propatation to shared
          # https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-bind-propagation
        - mountPath: /mnt/mfsdata:shared
          name: moosefs
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: worker
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      volumes:
      - hostPath:
          path: /dev/fuse
        name: fuse
      - hostPath:
          path: /mnt/disks/moosefs
        name: moosefs
  updateStrategy:
    type: OnDelete
...
